In [5]:
from sklearn.datasets import load_iris

In [6]:
X, y = load_iris(return_X_y = True)

**GOAL**: Make a model that predicts flower class (0,1,2) from measurements of petal/sepal.

In [9]:
from sklearn.datasets import load_boston
X_boston, y_boston = load_boston(return_X_y = True)

In [10]:
X_boston[0,:]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [12]:
y_boston[0] #price of the first house

24.0

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr = LinearRegression() # Just brings in the machinery, but doesn't compute

In [15]:
lr.fit(X_boston,y_boston) # Here the coefficients are actually calculated!

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
lr.coef_ # Coefficients calculated by model

array([-1.07170557e-01,  4.63952195e-02,  2.08602395e-02,  2.68856140e+00,
       -1.77957587e+01,  3.80475246e+00,  7.51061703e-04, -1.47575880e+00,
        3.05655038e-01, -1.23293463e-02, -9.53463555e-01,  9.39251272e-03,
       -5.25466633e-01])

In [18]:
lr.intercept_ # First "coefficient", theta_0

36.49110328036103

In [20]:
import numpy as np

In [31]:
np.dot(X_boston[17,:],lr.coef_)+lr.intercept_

16.909674898646244

In [32]:
y_boston[17]

17.5

In [25]:
y_pred = lr.predict(X_boston) #apply model to everything

In [29]:
# How well the model is doing?
from math import sqrt
rmse = sqrt(sum((y_pred-y_boston)**2)/len(y_boston))

In [30]:
rmse

4.679506300635516

**IRIS DATA**: Similar workflow, but just change the estimator.

In [34]:
# 0. Import the necessary model
from sklearn.linear_model import LogisticRegression

In [35]:
# 1. Create an instance of that model
logreg = LogisticRegression()

In [36]:
# 2. Give data to that model and use `fit`
logreg.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [37]:
# 3. Look at predictions. Two types of predictions in this case!
y_pred = logreg.predict(X) # same as before
y_probas = logreg.predict_proba(X)

In [38]:
y_pred[0]

0

In [39]:
y_probas[0]

array([8.79681649e-01, 1.20307538e-01, 1.08131372e-05])

In [40]:
y[0]

0

In [43]:
# 4. How well the model does? 
from sklearn.metrics import confusion_matrix

confusion_matrix(y,y_pred) #true and predicted value

array([[50,  0,  0],
       [ 0, 45,  5],
       [ 0,  1, 49]], dtype=int64)

In [51]:
x = [0,0,0]

In [52]:
x

[0, 0, 0]

In [53]:
y = x.copy()

In [54]:
y

[0, 0, 0]

In [55]:
x[1] = 'valentine'

In [56]:
y

[0, 0, 0]